---
# tasks file for openvpn-generic
- name: install apt packages
  apt:
    name:
      - python
      - python-setuptools
      - python-dev
      - build-essential
      - python-pip
      - python-apt
      - sshpass
      - rsync

- name: Install python modules
  pip:
    name:
      - ansible==2.8.5
      - pexpect==4.7.0

- name: Install OPENVPN
  apt:
    name: openvpn

- name: Create host pki dir
  file:
    path: "{{ host_pki_dir }}"
    state: directory
    mode: '0770'

- name: Generate diffie helman
  command: openssl dhparam -out {{ host_pki_dir }}/{{ dh }}.pem {{ dh_len }}
  args:
    creates: "{{ host_pki_dir }}/{{ dh }}.pem"
